version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stop_grace_period: 120s

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"