services:
  app:
    container_name: app_book_stealer
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: postgres_book_stealer
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: redis_book_stealer
    ports:
      - "6379:6379"

volumes:
  postgres-db: