services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stop_grace_period: 120s
    networks:
      - book_stealer_network
      - pg_network

  redis:
    image: redis:alpine
    restart: always
    networks:
      - book_stealer_network

networks:
  pg_network:
    external: true
  book_stealer_network:
    driver: bridge