// Code generated by MockGen. DO NOT EDIT.
// Source: book_stealer_tgbot/internal/service/bookStealerService (interfaces: Mailer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mailer.go -package=mocks . Mailer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendFile mocks base method.
func (m *MockMailer) SendFile(ctx context.Context, to, fileName string, fileContent []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFile", ctx, to, fileName, fileContent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFile indicates an expected call of SendFile.
func (mr *MockMailerMockRecorder) SendFile(ctx, to, fileName, fileContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFile", reflect.TypeOf((*MockMailer)(nil).SendFile), ctx, to, fileName, fileContent)
}
